# Generated by Django 6.0.1 on 2026-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_head', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=90)),
                ('Department', models.CharField(max_length=150)),
                ('Year', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smHead', models.CharField(max_length=50)),
                ('Head', models.CharField(max_length=50)),
                ('Head_Desc', models.CharField(max_length=50)),
                ('Head_link1', models.CharField(max_length=90)),
                ('Head_link2', models.CharField(max_length=90)),
                ('Head_link3', models.CharField(max_length=90)),
                ('Head_link4', models.CharField(max_length=90)),
                ('Head_link5', models.CharField(max_length=90)),
                ('Mail', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='lenguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_img', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.CharField(max_length=70)),
                ('pro_detail', models.TextField(max_length=220)),
                ('pro_link', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_img', models.CharField(max_length=60)),
                ('Card_hd', models.CharField(max_length=90)),
            ],
        ),
    ]
