# Generated by Django 6.0.1 on 2026-01-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='about_text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about_me',
            name='about_head',
            field=models.CharField(max_length=90),
        ),
    ]
