# Generated by Django 6.0.1 on 2026-01-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_about_me_about_text_alter_about_me_about_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='Head_Desc',
            field=models.TextField(),
        ),
    ]
