# Generated by Django 6.0.1 on 2026-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_hero_head_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Head_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
