# Generated by Django 6.0.1 on 2026-01-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_hero_head_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='about_img',
            field=models.FileField(max_length=90, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lenguage',
            name='language_img',
            field=models.FileField(max_length=70, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_img',
            field=models.FileField(max_length=70, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='Card_img',
            field=models.FileField(max_length=60, null=True, upload_to=''),
        ),
    ]
