# Generated by Django 6.0.1 on 2026-01-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_about_me_about_img_alter_lenguage_language_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_img', models.FileField(max_length=70, null=True, upload_to='')),
                ('test_text', models.TextField()),
            ],
        ),
    ]
