# Generated by Django 6.0.1 on 2026-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_email', models.TextField(max_length=50)),
                ('t_cnt', models.TextField(max_length=25)),
                ('t_loc', models.TextField(max_length=90)),
            ],
        ),
    ]
